require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.1'

def shared_pods
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # To enable Hermes on iOS, change `false` to `true` and then install pods.
    :hermes_enabled => false
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next few line.
  use_flipper!()

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
end


target 'appStarter' do
  shared_pods
  
  target 'appStarterTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'STAGING' do
  shared_pods
  inherit! :search_paths
end

target 'PROD' do
  shared_pods
  inherit! :search_paths
end

post_install do |installer|
  react_native_post_install(installer)
end
