//
// NOTE: THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
//

/* eslint-disable @typescript-eslint/no-var-requires */

import type { FC } from 'react'
import type { SvgProps } from 'react-native-svg'
import FastImage, { FastImageProps } from 'react-native-fast-image'
import type { ImageSourcePropType, ViewProps, ViewStyle, StyleProp } from 'react-native'

export type AssetsBitmapType = {
  imgCloseButton: ImageSourcePropType
  imgLogo: ImageSourcePropType
}

export type AssetsVectorType = {
  icnActivity: FC<SvgProps>
  icnArrow: FC<SvgProps>
  icnBackButton: FC<SvgProps>
  icnClose: FC<SvgProps>
  icnCopy: FC<SvgProps>
  icnEmail: FC<SvgProps>
  icnEyeClosed: FC<SvgProps>
  icnEyeOpen: FC<SvgProps>
  icnHome: FC<SvgProps>
  icnLock: FC<SvgProps>
  icnPen: FC<SvgProps>
  icnProfile: FC<SvgProps>
  icnReload: FC<SvgProps>
  icnSend: FC<SvgProps>
  icnSettings: FC<SvgProps>
  icnTips: FC<SvgProps>
  icnWifi: FC<SvgProps>
}

export interface IconPropsType {
  size?: number
  color?: string
  fill?: string
  stroke?: string
  style?: StyleProp<ViewStyle>
  testID?: ViewProps['testID']
}

export type IconType = typeof Icons[keyof typeof Icons]

export const Icons = {
  /**
   * ![icn_activity.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_activity.svg)
   */
  Activity: ({ size, fill, style, stroke, testID, color = 'transparent' }: IconPropsType): JSX.Element => {
    const Svg = require('./icn_activity.svg').default
    return (
      <Svg testID={testID} fill={fill || color} stroke={stroke || color} width={size} height={size} style={style} />
    )
  },
  /**
   * ![icn_arrow.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_arrow.svg)
   */ Arrow: ({ size, fill, style, stroke, testID, color = 'transparent' }: IconPropsType): JSX.Element => {
    const Svg = require('./icn_arrow.svg').default
    return (
      <Svg testID={testID} fill={fill || color} stroke={stroke || color} width={size} height={size} style={style} />
    )
  },
  /**
   * ![icn_back_button.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_back_button.svg)
   */ BackButton: ({ size, fill, style, stroke, testID, color = 'transparent' }: IconPropsType): JSX.Element => {
    const Svg = require('./icn_back_button.svg').default
    return (
      <Svg testID={testID} fill={fill || color} stroke={stroke || color} width={size} height={size} style={style} />
    )
  },
  /**
   * ![icn_close.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_close.svg)
   */ Close: ({ size, fill, style, stroke, testID, color = 'transparent' }: IconPropsType): JSX.Element => {
    const Svg = require('./icn_close.svg').default
    return (
      <Svg testID={testID} fill={fill || color} stroke={stroke || color} width={size} height={size} style={style} />
    )
  },
  /**
   * ![icn_copy.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_copy.svg)
   */ Copy: ({ size, fill, style, stroke, testID, color = 'transparent' }: IconPropsType): JSX.Element => {
    const Svg = require('./icn_copy.svg').default
    return (
      <Svg testID={testID} fill={fill || color} stroke={stroke || color} width={size} height={size} style={style} />
    )
  },
  /**
   * ![icn_email.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_email.svg)
   */ Email: ({ size, fill, style, stroke, testID, color = 'transparent' }: IconPropsType): JSX.Element => {
    const Svg = require('./icn_email.svg').default
    return (
      <Svg testID={testID} fill={fill || color} stroke={stroke || color} width={size} height={size} style={style} />
    )
  },
  /**
   * ![icn_eye_closed.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_eye_closed.svg)
   */ EyeClosed: ({ size, fill, style, stroke, testID, color = 'transparent' }: IconPropsType): JSX.Element => {
    const Svg = require('./icn_eye_closed.svg').default
    return (
      <Svg testID={testID} fill={fill || color} stroke={stroke || color} width={size} height={size} style={style} />
    )
  },
  /**
   * ![icn_eye_open.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_eye_open.svg)
   */ EyeOpen: ({ size, fill, style, stroke, testID, color = 'transparent' }: IconPropsType): JSX.Element => {
    const Svg = require('./icn_eye_open.svg').default
    return (
      <Svg testID={testID} fill={fill || color} stroke={stroke || color} width={size} height={size} style={style} />
    )
  },
  /**
   * ![icn_home.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_home.svg)
   */ Home: ({ size, fill, style, stroke, testID, color = 'transparent' }: IconPropsType): JSX.Element => {
    const Svg = require('./icn_home.svg').default
    return (
      <Svg testID={testID} fill={fill || color} stroke={stroke || color} width={size} height={size} style={style} />
    )
  },
  /**
   * ![icn_lock.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_lock.svg)
   */ Lock: ({ size, fill, style, stroke, testID, color = 'transparent' }: IconPropsType): JSX.Element => {
    const Svg = require('./icn_lock.svg').default
    return (
      <Svg testID={testID} fill={fill || color} stroke={stroke || color} width={size} height={size} style={style} />
    )
  },
  /**
   * ![icn_pen.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_pen.svg)
   */ Pen: ({ size, fill, style, stroke, testID, color = 'transparent' }: IconPropsType): JSX.Element => {
    const Svg = require('./icn_pen.svg').default
    return (
      <Svg testID={testID} fill={fill || color} stroke={stroke || color} width={size} height={size} style={style} />
    )
  },
  /**
   * ![icn_profile.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_profile.svg)
   */ Profile: ({ size, fill, style, stroke, testID, color = 'transparent' }: IconPropsType): JSX.Element => {
    const Svg = require('./icn_profile.svg').default
    return (
      <Svg testID={testID} fill={fill || color} stroke={stroke || color} width={size} height={size} style={style} />
    )
  },
  /**
   * ![icn_reload.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_reload.svg)
   */ Reload: ({ size, fill, style, stroke, testID, color = 'transparent' }: IconPropsType): JSX.Element => {
    const Svg = require('./icn_reload.svg').default
    return (
      <Svg testID={testID} fill={fill || color} stroke={stroke || color} width={size} height={size} style={style} />
    )
  },
  /**
   * ![icn_send.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_send.svg)
   */ Send: ({ size, fill, style, stroke, testID, color = 'transparent' }: IconPropsType): JSX.Element => {
    const Svg = require('./icn_send.svg').default
    return (
      <Svg testID={testID} fill={fill || color} stroke={stroke || color} width={size} height={size} style={style} />
    )
  },
  /**
   * ![icn_settings.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_settings.svg)
   */ Settings: ({ size, fill, style, stroke, testID, color = 'transparent' }: IconPropsType): JSX.Element => {
    const Svg = require('./icn_settings.svg').default
    return (
      <Svg testID={testID} fill={fill || color} stroke={stroke || color} width={size} height={size} style={style} />
    )
  },
  /**
   * ![icn_tips.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_tips.svg)
   */ Tips: ({ size, fill, style, stroke, testID, color = 'transparent' }: IconPropsType): JSX.Element => {
    const Svg = require('./icn_tips.svg').default
    return (
      <Svg testID={testID} fill={fill || color} stroke={stroke || color} width={size} height={size} style={style} />
    )
  },
  /**
   * ![icn_wifi.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_wifi.svg)
   */ Wifi: ({ size, fill, style, stroke, testID, color = 'transparent' }: IconPropsType): JSX.Element => {
    const Svg = require('./icn_wifi.svg').default
    return (
      <Svg testID={testID} fill={fill || color} stroke={stroke || color} width={size} height={size} style={style} />
    )
  },
}

export const Images = {
  /**
   * ![img_close_button.png](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/img_close_button.png)
   */
  CloseButton: (props: Omit<FastImageProps, 'source'>): JSX.Element => (
    <FastImage {...props} source={require('./img_close_button.png')} />
  ),
  /**
   * ![img_logo.png](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/img_logo.png)
   */ Logo: (props: Omit<FastImageProps, 'source'>): JSX.Element => (
    <FastImage {...props} source={require('./img_logo.png')} />
  ),
}

export const Assets = {
  /**
   * ![icn_activity.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_activity.svg)
   */
  icnActivity: require('./icn_activity.svg').default,
  /**
   * ![icn_arrow.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_arrow.svg)
   */
  icnArrow: require('./icn_arrow.svg').default,
  /**
   * ![icn_back_button.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_back_button.svg)
   */
  icnBackButton: require('./icn_back_button.svg').default,
  /**
   * ![icn_close.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_close.svg)
   */
  icnClose: require('./icn_close.svg').default,
  /**
   * ![icn_copy.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_copy.svg)
   */
  icnCopy: require('./icn_copy.svg').default,
  /**
   * ![icn_email.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_email.svg)
   */
  icnEmail: require('./icn_email.svg').default,
  /**
   * ![icn_eye_closed.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_eye_closed.svg)
   */
  icnEyeClosed: require('./icn_eye_closed.svg').default,
  /**
   * ![icn_eye_open.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_eye_open.svg)
   */
  icnEyeOpen: require('./icn_eye_open.svg').default,
  /**
   * ![icn_home.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_home.svg)
   */
  icnHome: require('./icn_home.svg').default,
  /**
   * ![icn_lock.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_lock.svg)
   */
  icnLock: require('./icn_lock.svg').default,
  /**
   * ![icn_pen.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_pen.svg)
   */
  icnPen: require('./icn_pen.svg').default,
  /**
   * ![icn_profile.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_profile.svg)
   */
  icnProfile: require('./icn_profile.svg').default,
  /**
   * ![icn_reload.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_reload.svg)
   */
  icnReload: require('./icn_reload.svg').default,
  /**
   * ![icn_send.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_send.svg)
   */
  icnSend: require('./icn_send.svg').default,
  /**
   * ![icn_settings.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_settings.svg)
   */
  icnSettings: require('./icn_settings.svg').default,
  /**
   * ![icn_tips.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_tips.svg)
   */
  icnTips: require('./icn_tips.svg').default,
  /**
   * ![icn_wifi.svg](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/icn_wifi.svg)
   */
  icnWifi: require('./icn_wifi.svg').default,
  /**
   * ![img_close_button.png](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/img_close_button.png)
   */
  imgCloseButton: require('./img_close_button.png'),
  /**
   * ![img_logo.png](file:///Users/charles/Desktop/Colorfy/react-native-colorfy-template/template/src/assets/img_logo.png)
   */
  imgLogo: require('./img_logo.png'),
}
